doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                schema_filter: ~^(?!sessions|number_sequences)~
                driver: "pdo_mysql"
                #server_version: "8.0"
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                mapping_types:
                    enum: string
                url: '%env(resolve:DATABASE_URL)%'
        types:
            email: FBS\CoreBundle\Doctrine\Type\EmailType
            question_type: FBS\CoreBundle\Doctrine\Type\QuestionTypeType
            survey_status: FBS\CoreBundle\Doctrine\Type\SurveyStatusType
            
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                dql:
                    string_functions:
                        JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains
                    datetime_functions:
                        DATE: DoctrineExtensions\Query\Mysql\Date
                        HOUR: DoctrineExtensions\Query\Mysql\Hour
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    main:
                        is_bundle: false
                        type: annotation
                        dir: "%kernel.project_dir%/src/FBS/CoreBundle/Entity"
                        prefix: 'FBS\CoreBundle\Entity'
                        alias: main