gesdinet_jwt_refresh_token:
    ttl: 2592000 # one month, updates on refresh
    ttl_update: true
    firewall: api
    token_parameter_name: refreshToken
    single_use: true # regenerate when consumed
