twig:
    default_path: '%kernel.project_dir%/src/Templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    #form_themes:
    #    - 'admin/common/forms/formHorizal.html.twig'
